# Этап 1: Сборка агента
FROM golang:latest AS builder

WORKDIR /app
COPY . /app
COPY ./examples/hacker/.env /app/.env

RUN go build -o agent examples/hacker/main.go

# Этап 2: Финальный образ
FROM kalilinux/kali-rolling

# Устанавливаем зависимости (если нужно)
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git curl wget metasploit-framework

# Копируем исполняемый файл из этапа сборки
COPY --from=builder /app/agent /app/agent
COPY --from=builder /app/.env /app/.env
WORKDIR /app
CMD ["./agent"]